// my-app/src/components/Navbar.jsx

function Navbar() {
  return (
    <nav className="navbar" role="navigation" aria-label="main navigation">
        <div className="navbar-brand">
            <a className="navbar-item" href="!#">
            <img src='logo192.png' width="50" height="100" alt="site logo" />
            </a>

            <a href="!#" role="button" className="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            </a>
        </div>

        <div id="navbarBasicExample" className="navbar-menu">
            <div className="navbar-start">
            <a href="!#" className="navbar-item">
                Home
            </a>

            <a href="!#" className="navbar-item">
                Documentation
            </a>

            <div className="navbar-item has-dropdown is-hoverable">
                <a href="!#" className="navbar-link">
                More
                </a>

                <div className="navbar-dropdown">
                <a href="!#" className="navbar-item">
                    About
                </a>
                <a href="!#" className="navbar-item">
                    Jobs
                </a>
                <a href="!#" className="navbar-item">
                    Contact
                </a>
                <hr className="navbar-divider" />
                <a href="!#"className="navbar-item">
                    Report an issue
                </a>
                </div>
            </div>
            </div>

            <div className="navbar-end">
            <div className="navbar-item">
                <div className="buttons">
                <a href="!#" className="button is-primary">
                    <strong>Sign up</strong>
                </a>
                <a href="!#" className="button is-light">
                    Log in
                </a>
                </div>
            </div>
            </div>
        </div>
</nav>
  )
}

export default Navbar

// my-vue-app/src/components/NavBar.vue
<template>
 <nav class="navbar is-light">
  <div class="navbar-brand">
    <a class="navbar-item" href="!#">
      <img src="../assets/logo.svg" alt="Bulma: a modern CSS framework based on Flexbox" width="112" height="28">
    </a>
    <div class="navbar-burger" data-target="navbarMobile">
      <span></span>
      <span></span>
      <span></span>
    </div>
  </div>

  <div id="navbarMobile" class="navbar-menu">
    <div class="navbar-start">
      <a class="navbar-item is-active" href="!#">
        Home
      </a>
      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link" href="!#">
          Docs
        </a>
        <div class="navbar-dropdown is-boxed">
          <a class="navbar-item" href="!#">
            Overview
          </a>
          <a class="navbar-item" href="!#">
            Modifiers
          </a>
          <a class="navbar-item" href="!#">
            Columns
          </a>
          <a class="navbar-item" href="!#">
            Layout
          </a>
        </div>
      </div>
    </div>

    <div class="navbar-end">
      <div class="navbar-item">
        <div class="field is-grouped">
          <p class="control">
            <a class="bd-tw-button button" data-social-network="Twitter" data-social-action="tweet" data-social-target="!#" target="_blank" href="https://twitter.com/intent/tweet?text=Bulma: a modern CSS framework based on Flexbox&amp;hashtags=bulmaio&amp;url=https://bulma.io&amp;via=jgthms">
              <span>
                Tweet
              </span>
            </a>
          </p>
          <p class="control">
            <a class="button is-primary" href="!#">
              <span>Download</span>
            </a>
          </p>
        </div>
      </div>
    </div>
  </div>
</nav>
  </template>
